version: "3.9"
services:
  #  proxy:
  #    image: nginx
  #    ports:
  #      - "8000:80"
  #      - "9000:9000"
  #    volumes:
  #      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #    depends_on:
  #      - hello
  #      - products
  #      - product_view

  container:
    build:
      context: ./container
    working_dir: /app
    ports:
      - "9000:9000"
    command: sh /usr/local/bin/spa-entrypoint.sh
    volumes:
      - ./spa-entrypoint.sh:/usr/local/bin/spa-entrypoint.sh
      - ./container:/app
      - modulesContainer:/app/node_modules

  hello:
    image: node:16-alpine
    working_dir: /app
    ports:
      - "8080:8080"
    command: sh /usr/local/bin/spa-entrypoint.sh
    volumes:
      - ./spa-entrypoint.sh:/usr/local/bin/spa-entrypoint.sh
      - ./hello:/app
      - modulesHello:/app/node_modules

  products:
    image: node:16-alpine
    working_dir: /app
    ports:
      - "8081:8080"
    command: sh /usr/local/bin/spa-entrypoint.sh
    volumes:
      - ./spa-entrypoint.sh:/usr/local/bin/spa-entrypoint.sh
      - ./products:/app
      - modulesProducts:/app/node_modules

  product_view:
    image: node:16-alpine
    working_dir: /app
    ports:
      - "8082:8080"
    command: sh /usr/local/bin/spa-entrypoint.sh
    volumes:
      - ./spa-entrypoint.sh:/usr/local/bin/spa-entrypoint.sh
      - ./product_view:/app
      - modulesProductView:/app/node_modules

volumes:
  modulesContainer:
  modulesHello:
  modulesProducts:
  modulesProductView:

